export type AuLender = {
  name: string;
  category: 'Bank SME' | 'Unsecured fintech' | 'SME unsecured' | 'Invoice finance' | 'Asset / equipment' | 'Line of credit' | 'Merchant cash advance' | 'Bridging' | 'SME / consolidation';
};

export const AU_LENDERS: AuLender[] = [
  { name: "ANZ Business", category: "Bank SME" },
  { name: "CommBank Business", category: "Bank SME" },
  { name: "Westpac Business", category: "Bank SME" },
  { name: "NAB Business", category: "Bank SME" },
  { name: "Bendigo Bank", category: "Bank SME" },
  { name: "BOQ Business", category: "Bank SME" },
  { name: "Suncorp Business", category: "Bank SME" },
  { name: "Macquarie Business", category: "Bank SME" },
  { name: "Prospa", category: "Unsecured fintech" },
  { name: "OnDeck", category: "Unsecured fintech" },
  { name: "Moula", category: "Unsecured fintech" },
  { name: "Lumi", category: "Unsecured fintech" },
  { name: "Bizcap", category: "SME unsecured" },
  { name: "GetCapital", category: "Unsecured fintech" },
  { name: "Capify", category: "SME unsecured" },
  { name: "Banjo Loans", category: "SME unsecured" },
  { name: "Shift", category: "SME / consolidation" },
  { name: "TruCap", category: "SME unsecured" },
  { name: "Skyecap", category: "SME unsecured" },
  { name: "Dynamoney", category: "SME unsecured" },
  { name: "Moneytech", category: "Line of credit" },
  { name: "Funds Now", category: "SME unsecured" },
  { name: "ScotPac", category: "Invoice finance" },
  { name: "Judo Bank", category: "Bank SME" },
  { name: "Zip Business", category: "Line of credit" },
  { name: "Grow Finance", category: "SME unsecured" },
  { name: "Butn", category: "Invoice finance" },
  { name: "Metro Finance", category: "Asset / equipment" },
  { name: "Pepper Money", category: "Asset / equipment" },
  { name: "Liberty Financial", category: "Asset / equipment" },
  { name: "Thinktank", category: "Bridging" },
  { name: "La Trobe Financial", category: "Bridging" },
  { name: "Resimac", category: "Asset / equipment" },
  { name: "Funding.com.au", category: "Bridging" },
  { name: "Multipli", category: "SME unsecured" },
  { name: "Earlypay", category: "Invoice finance" },
  { name: "Octet Finance", category: "Invoice finance" },
  { name: "Cashflow Finance", category: "Invoice finance" },
  { name: "MaxCap Group", category: "Bridging" },
  { name: "Spotcap", category: "SME unsecured" },
  { name: "Credabl", category: "Bank SME" },
];
