export type LenderProduct = {
  name: string;
  rateFrom?: number;
  rateTo?: number;
  rateText?: string;
  minLoan?: number;
  maxLoan?: number;
  minTermMonths?: number;
  maxTermMonths?: number;
  minTradingMonths?: number;
  minMonthlyRevenue?: number;
  minCreditScore?: number;
  decisionTime?: string;
  fundingTime?: string;
  repaymentFreq?: string;
  documentsRequired?: string;
  industriesExcluded?: string;
  notes?: string;
};

export type DetailedLender = {
  name: string;
  slug: string;
  phone: string;
  website: string;
  yearFounded?: string;
  productCount: number;
  minLoanAny: number;
  maxLoanAny: number;
  minTradingMonthsAny?: number;
  minMonthlyRevenueAny?: number;
  propertyRequired: 'no' | 'optional' | 'sometimes' | 'varies';
  fastestDecision?: string;
  fastestFunding?: string;
  hero: LenderProduct;
  products: LenderProduct[];
};

export const DETAILED_LENDERS: DetailedLender[] = [
  {
    name: "Prospa",
    slug: "prospa",
    phone: "1300 882 867",
    website: "https://www.prospa.com",
    yearFounded: "2012",
    productCount: 2,
    minLoanAny: 2000,
    maxLoanAny: 1000000,
    minTradingMonthsAny: 6,
    minMonthlyRevenueAny: 6000,
    propertyRequired: "optional",
    fastestDecision: "Same day",
    fastestFunding: "24 hours",
    hero: {
      name: "Small Business Loan",
      rateFrom: 8.9,
      rateTo: 21.5,
      minLoan: 2000,
      maxLoan: 500000,
      minTermMonths: 3,
      maxTermMonths: 36,
      minTradingMonths: 6,
      minMonthlyRevenue: 6000,
      decisionTime: "Same day",
      fundingTime: "24 hours",
      repaymentFreq: "Daily / weekly",
    },
    products: [
      {
        name: "Small Business Loan",
        rateFrom: 8.9,
        rateTo: 21.5,
        minLoan: 2000,
        maxLoan: 500000,
        minTermMonths: 3,
        maxTermMonths: 36,
        minTradingMonths: 6,
        minMonthlyRevenue: 6000,
        decisionTime: "Same day",
        fundingTime: "24 hours",
      },
      {
        name: "Line of Credit",
        rateFrom: 0,
        rateTo: 0,
        rateText: "Percentage of drawn amount",
        minLoan: 2000,
        maxLoan: 150000,
        minTradingMonths: 6,
        minMonthlyRevenue: 6000,
        decisionTime: "Same day",
        fundingTime: "24 hours",
      },
    ],
  },
  {
    name: "OnDeck",
    slug: "ondeck",
    phone: "1800 831 294",
    website: "https://www.ondeck.com.au",
    yearFounded: "2015",
    productCount: 2,
    minLoanAny: 10000,
    maxLoanAny: 500000,
    minTradingMonthsAny: 12,
    minMonthlyRevenueAny: 8333,
    propertyRequired: "no",
    fastestDecision: "30 minutes",
    fastestFunding: "2 hours",
    hero: {
      name: "Term Loan",
      rateFrom: 9.5,
      rateTo: 25.0,
      minLoan: 10000,
      maxLoan: 500000,
      minTermMonths: 6,
      maxTermMonths: 24,
      minTradingMonths: 12,
      minMonthlyRevenue: 8333,
      decisionTime: "30 minutes",
      fundingTime: "2 hours",
    },
    products: [
      {
        name: "Term Loan",
        rateFrom: 9.5,
        rateTo: 25.0,
        minLoan: 10000,
        maxLoan: 500000,
        minTermMonths: 6,
        maxTermMonths: 24,
        minTradingMonths: 12,
        minMonthlyRevenue: 8333,
        decisionTime: "30 minutes",
        fundingTime: "2 hours",
      },
      {
        name: "Line of Credit",
        rateFrom: 9.5,
        rateTo: 25.0,
        minLoan: 10000,
        maxLoan: 250000,
        minTradingMonths: 12,
        minMonthlyRevenue: 8333,
        decisionTime: "30 minutes",
        fundingTime: "Same day",
      },
    ],
  },
  {
    name: "Bizcap",
    slug: "bizcap",
    phone: "1300 922 223",
    website: "https://www.bizcap.com.au",
    yearFounded: "2017",
    productCount: 3,
    minLoanAny: 5000,
    maxLoanAny: 7500000,
    minTradingMonthsAny: 4,
    minMonthlyRevenueAny: 12000,
    propertyRequired: "sometimes",
    fastestDecision: "3 hours",
    fastestFunding: "Same day",
    hero: {
      name: "Business Loan",
      rateFrom: 11.0,
      rateTo: 35.0,
      minLoan: 5000,
      maxLoan: 7500000,
      minTermMonths: 3,
      maxTermMonths: 24,
      minTradingMonths: 4,
      minMonthlyRevenue: 12000,
      decisionTime: "3 hours",
      fundingTime: "Same day",
    },
    products: [
      {
        name: "Business Loan",
        rateFrom: 11.0,
        rateTo: 35.0,
        minLoan: 5000,
        maxLoan: 7500000,
        minTermMonths: 3,
        maxTermMonths: 24,
        minTradingMonths: 4,
        minMonthlyRevenue: 12000,
        decisionTime: "3 hours",
        fundingTime: "Same day",
      },
      {
        name: "Merchant Cash Advance",
        rateText: "Factor rate from 1.15",
        minLoan: 5000,
        maxLoan: 500000,
        minTradingMonths: 4,
        minMonthlyRevenue: 12000,
        decisionTime: "3 hours",
        fundingTime: "Same day",
      },
      {
        name: "Revenue-Based Finance",
        rateText: "Variable",
        minLoan: 5000,
        maxLoan: 2000000,
        minTradingMonths: 4,
        minMonthlyRevenue: 12000,
        decisionTime: "3 hours",
        fundingTime: "Same day",
      },
    ],
  },
  {
    name: "Capify",
    slug: "capify",
    phone: "1300 227 439",
    website: "https://www.capify.com.au",
    yearFounded: "2008",
    productCount: 2,
    minLoanAny: 5000,
    maxLoanAny: 1000000,
    minTradingMonthsAny: 6,
    minMonthlyRevenueAny: 10000,
    propertyRequired: "no",
    fastestDecision: "Hours",
    fastestFunding: "24 hours",
    hero: {
      name: "Business Loan",
      rateFrom: 13.95,
      rateTo: 34.95,
      minLoan: 5000,
      maxLoan: 1000000,
      minTermMonths: 3,
      maxTermMonths: 24,
      minTradingMonths: 6,
      minMonthlyRevenue: 10000,
      decisionTime: "Hours",
      fundingTime: "24 hours",
    },
    products: [
      {
        name: "Business Loan",
        rateFrom: 13.95,
        rateTo: 34.95,
        minLoan: 5000,
        maxLoan: 1000000,
        minTermMonths: 3,
        maxTermMonths: 24,
        minTradingMonths: 6,
        minMonthlyRevenue: 10000,
        decisionTime: "Hours",
        fundingTime: "24 hours",
      },
      {
        name: "Merchant Cash Advance",
        rateText: "Factor rate from 1.10",
        minLoan: 5000,
        maxLoan: 500000,
        minTradingMonths: 6,
        minMonthlyRevenue: 10000,
        decisionTime: "Hours",
        fundingTime: "24 hours",
      },
    ],
  },
  {
    name: "Moula",
    slug: "moula",
    phone: "1300 885 518",
    website: "https://www.moula.com.au",
    yearFounded: "2013",
    productCount: 2,
    minLoanAny: 10000,
    maxLoanAny: 500000,
    minTradingMonthsAny: 6,
    minMonthlyRevenueAny: 10000,
    propertyRequired: "no",
    fastestDecision: "Same day",
    fastestFunding: "24–48 hours",
    hero: {
      name: "Business Loan",
      rateFrom: 10.0,
      rateTo: 22.0,
      minLoan: 10000,
      maxLoan: 500000,
      minTermMonths: 6,
      maxTermMonths: 24,
      minTradingMonths: 6,
      minMonthlyRevenue: 10000,
      decisionTime: "Same day",
      fundingTime: "24–48 hours",
    },
    products: [
      {
        name: "Business Loan",
        rateFrom: 10.0,
        rateTo: 22.0,
        minLoan: 10000,
        maxLoan: 500000,
        minTermMonths: 6,
        maxTermMonths: 24,
        minTradingMonths: 6,
        minMonthlyRevenue: 10000,
        decisionTime: "Same day",
        fundingTime: "24–48 hours",
      },
      {
        name: "Line of Credit",
        rateFrom: 10.0,
        rateTo: 22.0,
        minLoan: 10000,
        maxLoan: 250000,
        minTradingMonths: 6,
        minMonthlyRevenue: 10000,
        decisionTime: "Same day",
        fundingTime: "24–48 hours",
      },
    ],
  },
  {
    name: "Lumi",
    slug: "lumi",
    phone: "1800 586 434",
    website: "https://www.lumi.com.au",
    yearFounded: "2018",
    productCount: 1,
    minLoanAny: 10000,
    maxLoanAny: 1000000,
    minTradingMonthsAny: 12,
    minMonthlyRevenueAny: 4166,
    propertyRequired: "no",
    fastestDecision: "24 hours",
    fastestFunding: "24 hours",
    hero: {
      name: "Business Loan",
      rateFrom: 12.0,
      rateTo: 30.0,
      minLoan: 10000,
      maxLoan: 1000000,
      minTermMonths: 3,
      maxTermMonths: 36,
      minTradingMonths: 12,
      minMonthlyRevenue: 4166,
      decisionTime: "24 hours",
      fundingTime: "24 hours",
    },
    products: [
      {
        name: "Business Loan",
        rateFrom: 12.0,
        rateTo: 30.0,
        minLoan: 10000,
        maxLoan: 1000000,
        minTermMonths: 3,
        maxTermMonths: 36,
        minTradingMonths: 12,
        minMonthlyRevenue: 4166,
        decisionTime: "24 hours",
        fundingTime: "24 hours",
      },
    ],
  },
  {
    name: "Funds Now",
    slug: "funds-now",
    phone: "1300 000 000",
    website: "https://www.fundsnow.com.au",
    productCount: 1,
    minLoanAny: 20000,
    maxLoanAny: 500000,
    minTradingMonthsAny: 6,
    minMonthlyRevenueAny: 20000,
    propertyRequired: "sometimes",
    fastestDecision: "2 hours",
    fastestFunding: "Same day",
    hero: {
      name: "Business Loan",
      rateFrom: 14.0,
      rateTo: 30.0,
      minLoan: 20000,
      maxLoan: 500000,
      minTermMonths: 3,
      maxTermMonths: 18,
      minTradingMonths: 6,
      minMonthlyRevenue: 20000,
      decisionTime: "2 hours",
      fundingTime: "Same day",
    },
    products: [
      {
        name: "Business Loan",
        rateFrom: 14.0,
        rateTo: 30.0,
        minLoan: 20000,
        maxLoan: 500000,
        minTermMonths: 3,
        maxTermMonths: 18,
        minTradingMonths: 6,
        minMonthlyRevenue: 20000,
        decisionTime: "2 hours",
        fundingTime: "Same day",
      },
    ],
  },
  {
    name: "Skyecap",
    slug: "skyecap",
    phone: "1300 000 000",
    website: "https://www.skyecap.com.au",
    productCount: 1,
    minLoanAny: 5000,
    maxLoanAny: 100000,
    minTradingMonthsAny: 3,
    minMonthlyRevenueAny: 10000,
    propertyRequired: "no",
    fastestDecision: "Hours",
    fastestFunding: "2 hours",
    hero: {
      name: "Business Loan",
      rateFrom: 15.0,
      rateTo: 35.0,
      minLoan: 5000,
      maxLoan: 100000,
      minTermMonths: 3,
      maxTermMonths: 12,
      minTradingMonths: 3,
      minMonthlyRevenue: 10000,
      decisionTime: "Hours",
      fundingTime: "2 hours",
    },
    products: [
      {
        name: "Business Loan",
        rateFrom: 15.0,
        rateTo: 35.0,
        minLoan: 5000,
        maxLoan: 100000,
        minTermMonths: 3,
        maxTermMonths: 12,
        minTradingMonths: 3,
        minMonthlyRevenue: 10000,
        decisionTime: "Hours",
        fundingTime: "2 hours",
      },
    ],
  },
  {
    name: "TruCap",
    slug: "trucap",
    phone: "1300 000 000",
    website: "https://www.trucap.com.au",
    productCount: 2,
    minLoanAny: 5000,
    maxLoanAny: 3000000,
    minTradingMonthsAny: 6,
    minMonthlyRevenueAny: 10000,
    propertyRequired: "optional",
    fastestDecision: "Hours",
    fastestFunding: "24 hours",
    hero: {
      name: "Business Loan",
      rateFrom: 12.0,
      rateTo: 28.0,
      minLoan: 5000,
      maxLoan: 3000000,
      minTermMonths: 3,
      maxTermMonths: 24,
      minTradingMonths: 6,
      minMonthlyRevenue: 10000,
      decisionTime: "Hours",
      fundingTime: "24 hours",
    },
    products: [
      {
        name: "Business Loan",
        rateFrom: 12.0,
        rateTo: 28.0,
        minLoan: 5000,
        maxLoan: 3000000,
        minTermMonths: 3,
        maxTermMonths: 24,
        minTradingMonths: 6,
        minMonthlyRevenue: 10000,
        decisionTime: "Hours",
        fundingTime: "24 hours",
      },
      {
        name: "Line of Credit",
        rateFrom: 12.0,
        rateTo: 28.0,
        minLoan: 5000,
        maxLoan: 500000,
        minTradingMonths: 6,
        minMonthlyRevenue: 10000,
        decisionTime: "Hours",
        fundingTime: "24 hours",
      },
    ],
  },
  {
    name: "Banjo Loans",
    slug: "banjo",
    phone: "1300 22 65 60",
    website: "https://www.banjoloans.com",
    yearFounded: "2014",
    productCount: 1,
    minLoanAny: 20000,
    maxLoanAny: 2000000,
    minTradingMonthsAny: 24,
    minMonthlyRevenueAny: 41666,
    propertyRequired: "optional",
    fastestDecision: "1–2 days",
    fastestFunding: "1–3 days",
    hero: {
      name: "Business Loan",
      rateFrom: 9.0,
      rateTo: 18.0,
      minLoan: 20000,
      maxLoan: 2000000,
      minTermMonths: 6,
      maxTermMonths: 36,
      minTradingMonths: 24,
      minMonthlyRevenue: 41666,
      decisionTime: "1–2 days",
      fundingTime: "1–3 days",
    },
    products: [
      {
        name: "Business Loan",
        rateFrom: 9.0,
        rateTo: 18.0,
        minLoan: 20000,
        maxLoan: 2000000,
        minTermMonths: 6,
        maxTermMonths: 36,
        minTradingMonths: 24,
        minMonthlyRevenue: 41666,
        decisionTime: "1–2 days",
        fundingTime: "1–3 days",
      },
    ],
  },
  {
    name: "Dynamoney",
    slug: "dynamoney",
    phone: "1300 000 000",
    website: "https://www.dynamoney.com",
    productCount: 1,
    minLoanAny: 5000,
    maxLoanAny: 500000,
    minMonthlyRevenueAny: 10000,
    propertyRequired: "no",
    fastestDecision: "Same day",
    fastestFunding: "24 hours",
    hero: {
      name: "Business Loan",
      rateFrom: 14.0,
      rateTo: 32.0,
      minLoan: 5000,
      maxLoan: 500000,
      minTermMonths: 3,
      maxTermMonths: 18,
      minMonthlyRevenue: 10000,
      decisionTime: "Same day",
      fundingTime: "24 hours",
    },
    products: [
      {
        name: "Business Loan",
        rateFrom: 14.0,
        rateTo: 32.0,
        minLoan: 5000,
        maxLoan: 500000,
        minTermMonths: 3,
        maxTermMonths: 18,
        minMonthlyRevenue: 10000,
        decisionTime: "Same day",
        fundingTime: "24 hours",
      },
    ],
  },
  {
    name: "Moneytech",
    slug: "moneytech",
    phone: "1300 232 224",
    website: "https://www.moneytech.com.au",
    productCount: 2,
    minLoanAny: 25000,
    maxLoanAny: 500000,
    propertyRequired: "no",
    fastestDecision: "24 hours",
    fastestFunding: "24–48 hours",
    hero: {
      name: "Line of Credit",
      rateFrom: 10.0,
      rateTo: 20.0,
      minLoan: 25000,
      maxLoan: 500000,
      minTermMonths: 12,
      maxTermMonths: 36,
      decisionTime: "24 hours",
      fundingTime: "24–48 hours",
    },
    products: [
      {
        name: "Line of Credit",
        rateFrom: 10.0,
        rateTo: 20.0,
        minLoan: 25000,
        maxLoan: 500000,
        minTermMonths: 12,
        maxTermMonths: 36,
        decisionTime: "24 hours",
        fundingTime: "24–48 hours",
      },
      {
        name: "Invoice Finance",
        rateText: "From 0.5% per invoice",
        minLoan: 25000,
        maxLoan: 500000,
        decisionTime: "24 hours",
        fundingTime: "24 hours",
      },
    ],
  },
  {
    name: "ScotPac",
    slug: "scotpac",
    phone: "1300 332 204",
    website: "https://www.scotpac.com.au",
    yearFounded: "1988",
    productCount: 3,
    minLoanAny: 10000,
    maxLoanAny: 150000000,
    minTradingMonthsAny: 12,
    propertyRequired: "no",
    fastestDecision: "24 hours",
    fastestFunding: "24 hours",
    hero: {
      name: "Business Loan",
      rateFrom: 6.5,
      rateTo: 15.0,
      minLoan: 10000,
      maxLoan: 5000000,
      minTermMonths: 12,
      maxTermMonths: 60,
      minTradingMonths: 12,
      decisionTime: "24 hours",
      fundingTime: "24 hours",
    },
    products: [
      {
        name: "Business Loan",
        rateFrom: 6.5,
        rateTo: 15.0,
        minLoan: 10000,
        maxLoan: 5000000,
        minTermMonths: 12,
        maxTermMonths: 60,
        minTradingMonths: 12,
        decisionTime: "24 hours",
        fundingTime: "24 hours",
      },
      {
        name: "Invoice Finance",
        rateText: "From 0.5% per invoice",
        minLoan: 50000,
        maxLoan: 150000000,
        minTradingMonths: 12,
        decisionTime: "24 hours",
        fundingTime: "24 hours",
      },
      {
        name: "Trade Finance",
        rateText: "Variable",
        minLoan: 100000,
        maxLoan: 50000000,
        minTradingMonths: 24,
        decisionTime: "48 hours",
        fundingTime: "48 hours",
      },
    ],
  },
  {
    name: "Shift",
    slug: "shift",
    phone: "1300 249 649",
    website: "https://www.shift.com.au",
    yearFounded: "2014",
    productCount: 1,
    minLoanAny: 5000,
    maxLoanAny: 2000000,
    minTradingMonthsAny: 24,
    minMonthlyRevenueAny: 20000,
    propertyRequired: "varies",
    fastestDecision: "24 hours",
    fastestFunding: "24 hours",
    hero: {
      name: "Business Loan",
      rateFrom: 9.5,
      rateTo: 20.0,
      minLoan: 5000,
      maxLoan: 2000000,
      minTermMonths: 6,
      maxTermMonths: 36,
      minTradingMonths: 24,
      minMonthlyRevenue: 20000,
      decisionTime: "24 hours",
      fundingTime: "24 hours",
    },
    products: [
      {
        name: "Business Loan",
        rateFrom: 9.5,
        rateTo: 20.0,
        minLoan: 5000,
        maxLoan: 2000000,
        minTermMonths: 6,
        maxTermMonths: 36,
        minTradingMonths: 24,
        minMonthlyRevenue: 20000,
        decisionTime: "24 hours",
        fundingTime: "24 hours",
      },
    ],
  },
];
